Add files via upload
Dora201/MIIRT.DBMS.Khobta.PriorityQueue pull request #2
Opened 2021-01-22 11:52 UTC by Dora201

Из всей программы не могу понять как написать функцию извлечения элемента (Dequeue()). HELP!

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +	int *element;
```cpp
private
    Element* head; 
    Element* tail;
    void Sort(); //Зачем у Вас входные параметры? 
    Я бы вообще его убрала в метод вставки
```
     
Честно говоря, совсем не понимаю Вашу логику(
Как у простой очереди (на списке, Вы же так хотите?), есть ссылка на начало и конец очереди, Вставка элемента (в Вашем случае, что написано,...две очереди?)

```cpp
public
     PriorityQueue();
    // Конструктор копирования
    PriorityQueue(const PriorityQueue<T>& queue);
    ~PriorityQueue();

    void Dequeue (T& value, int `(std::byte?)` priority) ;
    T& Enqueue();
    friend std::ostream& operator<< <T> (std::ostream&, const Enqueue<T>&);
```
Я так вижу на начальном этапе Ваш `API.` Все, что есть у Вас, не сходится с моим видинием жизни.
Имеется другое видение: есть массив Приоритетов и массив Данных. Соответственно имеется, все равно, голова и хвост (и данные, и приоритет), которые ссылаются на эти массивы. Что проще для Вас, выбирайте

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +
Необходим класс (структура), состоящая из двух элементов.  В идеале:
```cpp
template<class T>
class Element
{
    T element;
    int (хотя, здесь лучше использовать std::byte) priority;
    Element* next;

    explicit Element (const T& value);
}
```
Нельзя в Очередь с приоритетом добавлять элемент очереди и отдельно к нему приоритет. Они неразделимы внутри очереди.

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +void PriorityQueue::Show(PriorityQueue *list)
Не нужен. Переопределяйте оператор `<<`

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +		if (sort == false)
`if (sort == false)` тоже самое, что `if (!sort)`
Соответственно,
`if (sort == true)`  => `if (sort)`

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +void PriorityQueue::Sort(PriorityQueue *list)
Если Вас устраивает такой подход к сортировке (рекурсия), то ОК. Но, метод написан не в ООП стиле.

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +void PriorityQueue::Enqueue(PriorityQueue *elem, PriorityQueue *list)
Сортировка нужна только при Вставке элемента. Тогда:
   1.   Создаем новый `auto element = Element (value, priority);`
   2.   В цикле, начиная с хвоста, перебираем элементы, пока не найдем элемент с равным приоритетом
   3.   Вставляем (меняем ссылки на `next`) после найденного элемента
   4.    Если не нашли равного приоритета, то вставляемый элемент становится первым, т.е. головой
  
Сравниваем `element -> priority` и `current ->priority`. Вставляем `element`.
Так как это очередь, то по значению не сортирум. Последним пришел - последним вышел

2021-01-23 13:34 UTC, MarinaPaley commented on PriorityQueue.cpp
> +void PriorityQueue::Dequeue(PriorityQueue* list)
Точно в цикле удаляем элементы.
Можно написать закрытый метод `isEmpty` (`return this->head == nullptr;`)
Пока очередь не пустая, `this->Dequeue();`

2021-01-23 13:44 UTC, MarinaPaley requested changes
Мне все не понятно....Я вижу все по-другому.
Если сделать как я хочу, то метод `T& Dequeue();` просто возвращает первый элемент - голову, а головой станет `this->head->next`

2021-01-23 13:53 UTC, Dora201 commented on PriorityQueue.cpp
> +	int *element;
Добрый вечер, не поняла по поводу массива данных и массива приоритетов: вы предлагаете мне использовать два отдельных массива один - для данных, другой - для приоритетов, я правильно понимаю?

2021-01-24 17:35 UTC, MarinaPaley commented on PriorityQueue.cpp
> +	int *element;
Cуществует два варианта. Первый. как предлагаю я - через `private` структуру. Второй подход - классический. Да, там два массива. В одном - указатели на содержимое, во втором - указатели на приоритеты

2021-01-31 21:54 UTC, closed without merging

2021-01-31 21:54 UTC, MarinaPaley commented
Если ветка Вам не нужна, можете ее удалить.